apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: flask-gitops 
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: flask-gitops 
  template:
    metadata:
      labels:
        app: flask-gitops
    spec: 
      containers:
        - name: flask 
          image: anarkatomica1996/mi-app-gitops:REPLACE_WITH_TAG
          ports: 
          - containerPort: 5000 
          readinessProbe:
            httpGet:
              path: / 
              port: 5000 
            initialDelaySeconds: 5 
            periodSeconds: 10 