apiVersion: v1 
kind: Service 
metadata: 
  name: flask-gitops 
spec: 
  type: ClusterIP 
  selector: 
    app: flask-gitops
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 5000 
    