name: Build and Promote (GitOps)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app-repo
          file: ./app-repo/Dockerfile
          push: true
          tags: anarkatomica1996/mi-app-gitops:${{ github.sha }}

      - name: Clone GitOps repo
        run: |
          rm -rf gitops-repo
          git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/David-19960111/GitOps-Flask.git gitops-repo

      - name: List files in GitOps repo
        run: ls -R gitops-repo


      - name: Update kustomization.yaml
        run: |
          sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" gitops-repo/gitops-repo/apps/production/kustomization.yaml

      - name: Commit and push changes
        run: |
          cd gitops-repo/gitops-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/production/kustomization.yaml
          git commit -m "Deploy ${{ github.sha }}" || echo "No changes to commit"
          git push 

      - name: Sync with Argo CD
        if: success()
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USER }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure
          argocd app sync flask-gitops